apiVersion: v1
kind: Secret
metadata:
  name: {{ include "grafana.fullname" . }}-secret
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
type: Opaque
data:
  admin-password: {{ .Values.grafana.admin.password | b64enc | quote }}
