apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "jaeger.fullname" . }}
  labels:
    {{ include "jaeger.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{ include "jaeger.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{ include "jaeger.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: jaeger
        image: "{{ .Values.jaeger.image.repository }}:{{ .Values.jaeger.image.tag }}"
        imagePullPolicy: {{ .Values.jaeger.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 16686
          protocol: TCP
        {{ if .Values.jaeger.resources }}
        resources:
          {{ toYaml .Values.jaeger.resources | nindent 10 }}
        {{ end }}
        {{ if .Values.jaeger.storage }}
        volumeMounts:
        - name: jaeger-storage
          mountPath: /data
        {{ end }}
      {{ if .Values.jaeger.storage }}
      volumes:
      - name: jaeger-storage
        persistentVolumeClaim:
          claimName: {{ include "jaeger.fullname" . }}-pvc
      {{ end }}
