apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mariadb-database.fullname" . }}
  labels:
    {{- include "mariadb-database.labels" . | nindent 4 }}
    component: database
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "mariadb-database.selectorLabels" . | nindent 6 }}
      component: database
  template:
    metadata:
      labels:
        {{- include "mariadb-database.selectorLabels" . | nindent 8 }}
        component: database
    spec:
      containers:
      - name: mariadb
        image: "{{ .Values.database.image.repository }}:{{ .Values.database.image.tag }}"
        imagePullPolicy: {{ .Values.database.image.pullPolicy }}
        ports:
        - name: mariadb
          containerPort: 3306
          protocol: TCP
        env:
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: {{ include "mariadb-database.fullname" . }}-secret
              key: database-name
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: {{ include "mariadb-database.fullname" . }}-secret
              key: database-user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "mariadb-database.fullname" . }}-secret
              key: database-password
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "mariadb-database.fullname" . }}-secret
              key: root-password
        volumeMounts:
        - name: mariadb-storage
          mountPath: /var/lib/mysql
        resources:
          {{- toYaml .Values.database.resources | nindent 10 }}
      volumes:
      - name: mariadb-storage
        persistentVolumeClaim:
          claimName: {{ include "mariadb-database.fullname" . }}-pvc

